services:
  - type: web
    name: mirakle-platform
    env: python
    buildCommand: pip install -r requirements.txt && python init_database.py
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mirakle-db
          property: connectionString

databases:
  - name: mirakle-db
    databaseName: mirakle
    user: mirakle
